services:
  thedaotool:
    build: .
    container_name: ${CONTAINER_NAME:-thedaotool-backend}
    environment:
      - PORT=5050
      - NODE_ENV=${NODE_ENV}
      - FB_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
      - FB_REALTIME_DATABASE=${FB_REALTIME_DATABASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SERVER_URL=${SERVER_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - REDIS_URL=redis://redis:6379
      - PRIVY_APP_ID=${PRIVY_APP_ID}
      - PRIVY_APP_SECRET=${PRIVY_APP_SECRET}
      - SOLANA_CAIP2=${SOLANA_CAIP2}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - nginx_proxy_net

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nginx_proxy_net

networks:
  nginx_proxy_net:
    external: true
