services:
  bizzynetwork:
    build: .
    container_name: bizzy-backend
    environment:
      - PORT=5050
      - NODE_ENV=production
      - FB_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
      - FB_REALTIME_DATABASE=${FB_REALTIME_DATABASE}
      - FRONTEND_URL=${FRONTEND_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SERVER_URL=${SERVER_URL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - MAX_LOGIN_ATTEMPTS=${MAX_LOGIN_ATTEMPTS}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - REDIS_URL=redis://redis:6379
      - PRIVY_APP_ID=${PRIVY_APP_ID}
      - PRIVY_APP_SECRET=${PRIVY_APP_SECRET}
      - SOLANA_CAIP2=${SOLANA_CAIP2}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - LOG_LEVEL=info
      - LOG_TO_FILE=false
      - LOG_FILE=logs/app.log
      - LOG_TO_LOKI=true
      - LOKI_URL=http://loki:3100
    restart: unless-stopped
    networks:
      - nginx_proxy_net

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nginx_proxy_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - nginx_proxy_net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
    command: -config.file=/etc/promtail/config.yml
    networks:
      - nginx_proxy_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    depends_on:
      - loki
    networks:
      - nginx_proxy_net

networks:
  nginx_proxy_net:
    external: true
